Fix libpciaccess linking issue
On some platforms the linking stage may fail with the following message:
con_pci.o: In function `pci_device_init':
con_pci.c:(.text+0x1e3): undefined reference to `pci_device_map_range'
con_pci.o: In function `pci_device_cleanup':
con_pci.c:(.text+0x2ae): undefined reference to `pci_device_unmap_range'
con_pci.o: In function `pci_init':
con_pci.c:(.text+0x5f1): undefined reference to `pci_system_init'
con_pci.c:(.text+0x633): undefined reference to
`pci_slot_match_iterator_create'
con_pci.c:(.text+0x676): undefined reference to `pci_device_next'
con_pci.c:(.text+0x686): undefined reference to `pci_iterator_destroy'
con_pci.c:(.text+0x6c4): undefined reference to `pci_device_probe'
con_pci.c:(.text+0x744): undefined reference to `pci_system_cleanup'
con_pci.o: In function `pci_clean':
con_pci.c:(.text+0x77c): undefined reference to `pci_system_cleanup'
collect2: error: ld returned 1 exit status

This issue is caused by the wrong CC arguments order. Instruction
to link with libpciaccess (-lpciaccess) goes before the object file that
import its functions and linker is unable to found required symbols. Fix
this issue by correcting arguments order in the CC invocation line.

Reported-and-tested-by: Kevin Keijzer
Fixes: https://github.com/rsa9000/atheepmgr/issues/2